spring.application.name=easymockserver

application.title=easy mock server
application.version=1.1

server.port=8080
server.http2.enabled=true

logging.level.com.sustaining=${LOGGING_LEVEL_APP:WARN}

management.server.port=${MONITORING_PORT:9000}
management.endpoints.web.exposure.include=*